---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythingllm
  template:
    metadata:
      labels:
        app: anythingllm
    spec:
      containers:
      - name: anythingllm
        image: 192.168.49.1:5000/anythingllm:latest
        volumeMounts:
          - mountPath: /app/server/storage
            name: anythingllm-volume
          - mountPath: /app/server/.env
            name: anythingllm-env
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        ports:
        - containerPort: 3001
      volumes:
      - name: anythingllm-volume
        persistentVolumeClaim:
          claimName: anythingllm-pvc
      - name: anythingllm-env
        hostPath:
          path: /tmp/hostpath-provisioner/default/anythingllm-pvc/.env
---
apiVersion: v1
kind: Service
metadata:
  name: anythingllm-service
spec:
  type: LoadBalancer
  ports:
  - name: anythingllm
    protocol: TCP
    port: 80
    targetPort: 3001
  selector:
    app: anythingllm
# --- 
# apiVersion: v1
# kind: Service
# metadata:
#   name: anythingllm-service
# spec:
#   ports:
#   - name: ollama
#     protocol: TCP
#     port: 11434
#     targetPort: 11434
#   - name: anythingllm
#     protocol: TCP
#     port: 3001
#     targetPort: 3001
#   selector:
#     app: anythingllm-ollama
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: anythingllm-ingress
#   namespace: default
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /anythingllm
#         pathType: Prefix
#         backend:
#           service:
#             name: anythingllm-service
#             port:
#               number: 3001
#       - path: /ollama
#         pathType: Prefix
#         backend:
#           service:
#             name: anythingllm-service
#             port:
#               number: 11434


  
