---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: 192.168.49.1:5000/ollama:latest
        ports:
        - containerPort: 11434
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-volume
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
      volumes:
      - name: ollama-volume
        persistentVolumeClaim:
          claimName: ollama-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: LoadBalancer
  ports:
  - name: ollama
    protocol: TCP
    port: 11434
    targetPort: 11434
  selector:
    app: ollama
# --- 
# apiVersion: v1
# kind: Service
# metadata:
#   name: anythingllm-service
# spec:
#   ports:
#   - name: ollama
#     protocol: TCP
#     port: 11434
#     targetPort: 11434
#   - name: anythingllm
#     protocol: TCP
#     port: 3001
#     targetPort: 3001
#   selector:
#     app: anythingllm-ollama
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: anythingllm-ingress
#   namespace: default
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /anythingllm
#         pathType: Prefix
#         backend:
#           service:
#             name: anythingllm-service
#             port:
#               number: 3001
#       - path: /ollama
#         pathType: Prefix
#         backend:
#           service:
#             name: anythingllm-service
#             port:
#               number: 11434


  
